---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sateales/public_html/portfolio/
    - /bin/cp /home/sateales/repositories/portfolio/index.html $DEPLOYPATH
    - /bin/cp -r /home/sateales/repositories/portfolio/img $DEPLOYPATH
    - /bin/cp -r /home/sateales/repositories/portfolio/css $DEPLOYPATH